### PR TITLE
Add suport for 'Autodesk.AEC.ModelData' role.

### PR DESCRIPTION
**Pull request by nrayann**
Last monday this role started throwing an exception while translating a file that I am used to translate everyday in my app development.

### CODE REVIEW

**Comment by nrayann** [comment]
@augustogoncalves Would anyone else be more available to indicate to review this PR?

cc @ogaryu

**Comment by nrayann** [comment]
@augustogoncalves Is Packagist Auto-Updated Disabled? If so, could you update?

I updated the repository by dev-master but this merge didn't come.

cc @ogaryu

**Comment by augustogoncalves** [comment]
@nrayann can you please post in English so @ogaryu can follow up? Obrigado!

**Comment by ogaryu** [comment]
I updated the repository on Packagist now. Would you check this change?

**Comment by nrayann** [comment]
@ogaryu thanks.

**Comment by kamina1233** [comment]
Thanks this works like a charm

**Pull request merged**
